# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bispace.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core_pb2 as core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bispace.proto',
  package='org.swarmwalker.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbispace.proto\x12\x18org.swarmwalker.messages\x1a\ncore.proto\"7\n\x06\x42iGrid\x12-\n\x05items\x18\x01 \x03(\x0b\x32\x1e.org.swarmwalker.messages.Cell\"\xdc\x01\n\x04\x43\x65ll\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\x04pose\x18\x02 \x01(\x0b\x32\x1e.org.swarmwalker.messages.Pose\x12,\n\x04size\x18\x03 \x01(\x0b\x32\x1e.org.swarmwalker.messages.Size\x12>\n\nattributes\x18\x06 \x03(\x0b\x32*.org.swarmwalker.messages.Cell.DataPayload\x1a,\n\x0b\x44\x61taPayload\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\tb\x06proto3'
  ,
  dependencies=[core__pb2.DESCRIPTOR,])




_BIGRID = _descriptor.Descriptor(
  name='BiGrid',
  full_name='org.swarmwalker.messages.BiGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='org.swarmwalker.messages.BiGrid.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=110,
)


_CELL_DATAPAYLOAD = _descriptor.Descriptor(
  name='DataPayload',
  full_name='org.swarmwalker.messages.Cell.DataPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='org.swarmwalker.messages.Cell.DataPayload.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='org.swarmwalker.messages.Cell.DataPayload.payload', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=333,
)

_CELL = _descriptor.Descriptor(
  name='Cell',
  full_name='org.swarmwalker.messages.Cell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.swarmwalker.messages.Cell.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='org.swarmwalker.messages.Cell.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='org.swarmwalker.messages.Cell.size', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='org.swarmwalker.messages.Cell.attributes', index=3,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CELL_DATAPAYLOAD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=333,
)

_BIGRID.fields_by_name['items'].message_type = _CELL
_CELL_DATAPAYLOAD.containing_type = _CELL
_CELL.fields_by_name['pose'].message_type = core__pb2._POSE
_CELL.fields_by_name['size'].message_type = core__pb2._SIZE
_CELL.fields_by_name['attributes'].message_type = _CELL_DATAPAYLOAD
DESCRIPTOR.message_types_by_name['BiGrid'] = _BIGRID
DESCRIPTOR.message_types_by_name['Cell'] = _CELL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BiGrid = _reflection.GeneratedProtocolMessageType('BiGrid', (_message.Message,), {
  'DESCRIPTOR' : _BIGRID,
  '__module__' : 'bispace_pb2'
  # @@protoc_insertion_point(class_scope:org.swarmwalker.messages.BiGrid)
  })
_sym_db.RegisterMessage(BiGrid)

Cell = _reflection.GeneratedProtocolMessageType('Cell', (_message.Message,), {

  'DataPayload' : _reflection.GeneratedProtocolMessageType('DataPayload', (_message.Message,), {
    'DESCRIPTOR' : _CELL_DATAPAYLOAD,
    '__module__' : 'bispace_pb2'
    # @@protoc_insertion_point(class_scope:org.swarmwalker.messages.Cell.DataPayload)
    })
  ,
  'DESCRIPTOR' : _CELL,
  '__module__' : 'bispace_pb2'
  # @@protoc_insertion_point(class_scope:org.swarmwalker.messages.Cell)
  })
_sym_db.RegisterMessage(Cell)
_sym_db.RegisterMessage(Cell.DataPayload)


# @@protoc_insertion_point(module_scope)
