syntax = "proto3";

package org.swarmwalker.messages;


enum Unit {
  Millimeter = 0;
  Centimeter = 1;
  Meter = 2;
}


enum Type {
  Cartesian = 0;
  Quaternion = 1;
}


message Size {
  Unit unit = 1;      // unit
  float width = 2;    // width
  float length = 3;   // length
  float height = 4;   // height
}


message Pose {
  Type type = 1;      // coordinate type
  float x = 2;        // X coordinate
  float y = 3;        // Y coordinate
  float z = 4;        // Z coordinate
  float w = 5;        // quaternion W component
}